/* ============================================
   ZINTAGROW — PRODUCTS DATA (products.js)
   Yahan se saare products manage karo.
   URL update karna ho toh sirf is file mein karo.
   ============================================ */

const PRODUCTS = [
  {
    id: 'neobiz-theme',
    name: 'NeoBiz — Business & Agency Theme',
    category: 'theme',
    categoryLabel: 'WordPress Theme',
    price: 799,
    originalPrice: 2499,
    badge: 'hot',
    badgeText: '🔥 Hot',
    sales: 342,
    rating: 5,
    reviews: 48,
    icon: '🎨',
    previewUrl: 'https://demo.zintagrow.com/neobiz',       // ← apna live demo URL yahan lagao
    detailsUrl: 'https://zintagrow.com/products/neobiz',   // ← product page URL
    desc: 'Modern multipurpose business theme with 15+ demo pages, Elementor support aur one-click install. Agencies aur freelancers ke liye perfect.',
    meta: ['📥 342 Sales', '🔄 Lifetime Updates', '✅ GPL License'],
    thumbBg: 'linear-gradient(135deg,#1a1a4e,#2d1b69)',
  },
  {
    id: 'portfoliox-theme',
    name: 'PortfolioX — Creative Portfolio Theme',
    category: 'theme',
    categoryLabel: 'WordPress Theme',
    price: 599,
    originalPrice: 1999,
    badge: 'new',
    badgeText: '✨ New',
    sales: 128,
    rating: 5,
    reviews: 21,
    icon: '🎨',
    previewUrl: 'https://demo.zintagrow.com/portfoliox',
    detailsUrl: 'https://zintagrow.com/products/portfoliox',
    desc: 'Freelancers aur agencies ke liye dark/light portfolio theme with smooth GSAP animations aur 8+ portfolio layouts.',
    meta: ['📥 128 Sales', '🔄 Lifetime Updates', '📱 Fully Responsive'],
    thumbBg: 'linear-gradient(135deg,#0d1a2e,#1a0d2d)',
  },
  {
    id: 'speedboost-pro',
    name: 'SpeedBoost Pro — WP Performance Plugin',
    category: 'plugin',
    categoryLabel: 'WordPress Plugin',
    price: 499,
    originalPrice: 1499,
    badge: 'popular',
    badgeText: '⚡ Popular',
    sales: 891,
    rating: 5,
    reviews: 134,
    icon: '🔌',
    previewUrl: 'https://zintagrow.com/demo/speedboost',
    detailsUrl: 'https://zintagrow.com/products/speedboost-pro',
    desc: 'Ek click mein WordPress 90+ speed score pao. Caching, image optimization, lazy load, DB cleanup — sab in one plugin.',
    meta: ['📥 891 Sales', '🔌 Easy Setup', '🔄 Auto Updates'],
    thumbBg: 'linear-gradient(135deg,#0a1a1a,#0d2d1a)',
  },
  {
    id: 'seo-master-toolkit',
    name: 'SEO Master Toolkit — 2024 Edition',
    category: 'seo',
    categoryLabel: 'SEO Tool / Checklist',
    price: 299,
    originalPrice: 999,
    badge: 'sale',
    badgeText: '💰 Sale',
    sales: 1200,
    rating: 4,
    reviews: 209,
    icon: '📊',
    previewUrl: 'https://zintagrow.com/preview/seo-toolkit',
    detailsUrl: 'https://zintagrow.com/products/seo-toolkit',
    desc: 'Complete SEO audit checklist, keyword research templates, backlink tracker aur 6 mahine ki strategy guide. PDF + Excel format.',
    meta: ['📥 1.2k Downloads', '📄 PDF + Excel', '🔄 Quarterly Updates'],
    thumbBg: 'linear-gradient(135deg,#1a1a10,#1a2d10)',
  },
  {
    id: 'convertkit-templates',
    name: 'ConvertKit Pro — Landing Page Templates',
    category: 'template',
    categoryLabel: 'Elementor Template Kit',
    price: 449,
    originalPrice: 1299,
    badge: 'new',
    badgeText: '✨ New',
    sales: 567,
    rating: 5,
    reviews: 88,
    icon: '📄',
    previewUrl: 'https://demo.zintagrow.com/convertkit',
    detailsUrl: 'https://zintagrow.com/products/convertkit-templates',
    desc: '20+ high-converting Elementor landing page templates — leads, sales, webinar, course aur agency pages. Drag & drop ready.',
    meta: ['📥 567 Downloads', '📦 20+ Pages', '✏️ Elementor'],
    thumbBg: 'linear-gradient(135deg,#0d1a30,#1a102d)',
  },
  {
    id: 'ai-tools',
    name: 'AI Tools - Website Mentor',
    category: 'ai tools',
    categoryLabel: 'Ai Tools',
    price: 499,
    originalPrice: 1499,
    badge: 'popular',
    badgeText: '⚡ Popular',
    sales: 891,
    rating: 5,
    reviews: 134,
    icon: '🔌',
    previewUrl: 'https://zintagrow.com/demo/speedboost',
    detailsUrl: 'https://zintagrow.com/products/speedboost-pro',
    desc: 'Ek click mein WordPress 90+ speed score pao. Caching, image optimization, lazy load, DB cleanup — sab in one plugin.',
    meta: ['📥 891 Sales', '🔌 Easy Setup', '🔄 Auto Updates'],
    thumbBg: 'linear-gradient(135deg,#0a1a1a,#0d2d1a)',
  },
  {
    id: 'zintacache-lite',
    name: 'ZintaCache Lite — Free Caching Plugin',
    category: 'plugin free',
    categoryLabel: 'Free WordPress Plugin',
    price: 0,
    originalPrice: null,
    badge: 'free',
    badgeText: '🎁 Free',
    sales: 3400,
    rating: 4,
    reviews: 312,
    icon: '🔌',
    previewUrl: 'https://wordpress.org/plugins/zintacache-lite',   // ← WP.org link
    detailsUrl: 'https://zintagrow.com/products/zintacache-lite',
    desc: 'Humara free caching plugin jo aapki WordPress site ko instantly fast banata hai. No complex config needed — ek click setup!',
    meta: ['📥 3.4k Downloads', '⭐ WP.org Listed', '🛡️ Secure Code'],
    thumbBg: 'linear-gradient(135deg,#0a1a2d,#0d0a1a)',
  },
];

/* Bundle data */
const BUNDLE = {
  name: 'Ultimate Starter Bundle',
  previewUrl: 'https://zintagrow.com/bundle/starter-pack',
  detailsUrl: 'https://zintagrow.com/bundle/starter-pack',
};
